// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v5.28.2
// source: store_service.proto

package store

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ChunkSize int32

const (
	ChunkSize_EMPTY ChunkSize = 0
	ChunkSize_MAX   ChunkSize = 2048
)

// Enum value maps for ChunkSize.
var (
	ChunkSize_name = map[int32]string{
		0:    "EMPTY",
		2048: "MAX",
	}
	ChunkSize_value = map[string]int32{
		"EMPTY": 0,
		"MAX":   2048,
	}
)

func (x ChunkSize) Enum() *ChunkSize {
	p := new(ChunkSize)
	*p = x
	return p
}

func (x ChunkSize) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ChunkSize) Descriptor() protoreflect.EnumDescriptor {
	return file_store_service_proto_enumTypes[0].Descriptor()
}

func (ChunkSize) Type() protoreflect.EnumType {
	return &file_store_service_proto_enumTypes[0]
}

func (x ChunkSize) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ChunkSize.Descriptor instead.
func (ChunkSize) EnumDescriptor() ([]byte, []int) {
	return file_store_service_proto_rawDescGZIP(), []int{0}
}

type TxIsoLevel int32

const (
	TxIsoLevel_ISO_LEVEL_READ_UNCOMMITTED TxIsoLevel = 0
	TxIsoLevel_ISO_LEVEL_READ_COMMITTED   TxIsoLevel = 1
	TxIsoLevel_ISO_LEVEL_REPEATABLE_READ  TxIsoLevel = 2
	TxIsoLevel_ISO_LEVEL_SERIALIZABLE     TxIsoLevel = 3
)

// Enum value maps for TxIsoLevel.
var (
	TxIsoLevel_name = map[int32]string{
		0: "ISO_LEVEL_READ_UNCOMMITTED",
		1: "ISO_LEVEL_READ_COMMITTED",
		2: "ISO_LEVEL_REPEATABLE_READ",
		3: "ISO_LEVEL_SERIALIZABLE",
	}
	TxIsoLevel_value = map[string]int32{
		"ISO_LEVEL_READ_UNCOMMITTED": 0,
		"ISO_LEVEL_READ_COMMITTED":   1,
		"ISO_LEVEL_REPEATABLE_READ":  2,
		"ISO_LEVEL_SERIALIZABLE":     3,
	}
)

func (x TxIsoLevel) Enum() *TxIsoLevel {
	p := new(TxIsoLevel)
	*p = x
	return p
}

func (x TxIsoLevel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TxIsoLevel) Descriptor() protoreflect.EnumDescriptor {
	return file_store_service_proto_enumTypes[1].Descriptor()
}

func (TxIsoLevel) Type() protoreflect.EnumType {
	return &file_store_service_proto_enumTypes[1]
}

func (x TxIsoLevel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TxIsoLevel.Descriptor instead.
func (TxIsoLevel) EnumDescriptor() ([]byte, []int) {
	return file_store_service_proto_rawDescGZIP(), []int{1}
}

type Seek_Direction int32

const (
	Seek_SeekStart   Seek_Direction = 0
	Seek_SeekCurrent Seek_Direction = 1
	Seek_SeekEnd     Seek_Direction = 2
)

// Enum value maps for Seek_Direction.
var (
	Seek_Direction_name = map[int32]string{
		0: "SeekStart",
		1: "SeekCurrent",
		2: "SeekEnd",
	}
	Seek_Direction_value = map[string]int32{
		"SeekStart":   0,
		"SeekCurrent": 1,
		"SeekEnd":     2,
	}
)

func (x Seek_Direction) Enum() *Seek_Direction {
	p := new(Seek_Direction)
	*p = x
	return p
}

func (x Seek_Direction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Seek_Direction) Descriptor() protoreflect.EnumDescriptor {
	return file_store_service_proto_enumTypes[2].Descriptor()
}

func (Seek_Direction) Type() protoreflect.EnumType {
	return &file_store_service_proto_enumTypes[2]
}

func (x Seek_Direction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Seek_Direction.Descriptor instead.
func (Seek_Direction) EnumDescriptor() ([]byte, []int) {
	return file_store_service_proto_rawDescGZIP(), []int{1, 0}
}

type FileHeader struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// Deprecated: Marked as deprecated in store_service.proto.
	Size uint64 `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
}

func (x *FileHeader) Reset() {
	*x = FileHeader{}
	if protoimpl.UnsafeEnabled {
		mi := &file_store_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FileHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileHeader) ProtoMessage() {}

func (x *FileHeader) ProtoReflect() protoreflect.Message {
	mi := &file_store_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileHeader.ProtoReflect.Descriptor instead.
func (*FileHeader) Descriptor() ([]byte, []int) {
	return file_store_service_proto_rawDescGZIP(), []int{0}
}

func (x *FileHeader) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

// Deprecated: Marked as deprecated in store_service.proto.
func (x *FileHeader) GetSize() uint64 {
	if x != nil {
		return x.Size
	}
	return 0
}

type Seek struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Offset int64          `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	Dir    Seek_Direction `protobuf:"varint,2,opt,name=dir,proto3,enum=store.Seek_Direction" json:"dir,omitempty"`
}

func (x *Seek) Reset() {
	*x = Seek{}
	if protoimpl.UnsafeEnabled {
		mi := &file_store_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Seek) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Seek) ProtoMessage() {}

func (x *Seek) ProtoReflect() protoreflect.Message {
	mi := &file_store_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Seek.ProtoReflect.Descriptor instead.
func (*Seek) Descriptor() ([]byte, []int) {
	return file_store_service_proto_rawDescGZIP(), []int{1}
}

func (x *Seek) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *Seek) GetDir() Seek_Direction {
	if x != nil {
		return x.Dir
	}
	return Seek_SeekStart
}

type DataChunk struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Chunk []byte `protobuf:"bytes,1,opt,name=chunk,proto3" json:"chunk,omitempty"`
	Pos   *Seek  `protobuf:"bytes,2,opt,name=pos,proto3" json:"pos,omitempty"`
}

func (x *DataChunk) Reset() {
	*x = DataChunk{}
	if protoimpl.UnsafeEnabled {
		mi := &file_store_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DataChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataChunk) ProtoMessage() {}

func (x *DataChunk) ProtoReflect() protoreflect.Message {
	mi := &file_store_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataChunk.ProtoReflect.Descriptor instead.
func (*DataChunk) Descriptor() ([]byte, []int) {
	return file_store_service_proto_rawDescGZIP(), []int{2}
}

func (x *DataChunk) GetChunk() []byte {
	if x != nil {
		return x.Chunk
	}
	return nil
}

func (x *DataChunk) GetPos() *Seek {
	if x != nil {
		return x.Pos
	}
	return nil
}

type SetFileRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Data:
	//
	//	*SetFileRequest_Header
	//	*SetFileRequest_Chunk
	Data isSetFileRequest_Data `protobuf_oneof:"data"`
}

func (x *SetFileRequest) Reset() {
	*x = SetFileRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_store_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetFileRequest) ProtoMessage() {}

func (x *SetFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_store_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetFileRequest.ProtoReflect.Descriptor instead.
func (*SetFileRequest) Descriptor() ([]byte, []int) {
	return file_store_service_proto_rawDescGZIP(), []int{3}
}

func (m *SetFileRequest) GetData() isSetFileRequest_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (x *SetFileRequest) GetHeader() *FileHeader {
	if x, ok := x.GetData().(*SetFileRequest_Header); ok {
		return x.Header
	}
	return nil
}

func (x *SetFileRequest) GetChunk() []byte {
	if x, ok := x.GetData().(*SetFileRequest_Chunk); ok {
		return x.Chunk
	}
	return nil
}

type isSetFileRequest_Data interface {
	isSetFileRequest_Data()
}

type SetFileRequest_Header struct {
	Header *FileHeader `protobuf:"bytes,1,opt,name=header,proto3,oneof"`
}

type SetFileRequest_Chunk struct {
	Chunk []byte `protobuf:"bytes,2,opt,name=chunk,proto3,oneof"`
}

func (*SetFileRequest_Header) isSetFileRequest_Data() {}

func (*SetFileRequest_Chunk) isSetFileRequest_Data() {}

type SetFileResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SetFileResponse) Reset() {
	*x = SetFileResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_store_service_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetFileResponse) ProtoMessage() {}

func (x *SetFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_store_service_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetFileResponse.ProtoReflect.Descriptor instead.
func (*SetFileResponse) Descriptor() ([]byte, []int) {
	return file_store_service_proto_rawDescGZIP(), []int{4}
}

type GetFileRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *GetFileRequest) Reset() {
	*x = GetFileRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_store_service_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFileRequest) ProtoMessage() {}

func (x *GetFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_store_service_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFileRequest.ProtoReflect.Descriptor instead.
func (*GetFileRequest) Descriptor() ([]byte, []int) {
	return file_store_service_proto_rawDescGZIP(), []int{5}
}

func (x *GetFileRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type GetFileResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Data:
	//
	//	*GetFileResponse_Chunk
	//	*GetFileResponse_Header
	Data isGetFileResponse_Data `protobuf_oneof:"data"`
}

func (x *GetFileResponse) Reset() {
	*x = GetFileResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_store_service_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFileResponse) ProtoMessage() {}

func (x *GetFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_store_service_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFileResponse.ProtoReflect.Descriptor instead.
func (*GetFileResponse) Descriptor() ([]byte, []int) {
	return file_store_service_proto_rawDescGZIP(), []int{6}
}

func (m *GetFileResponse) GetData() isGetFileResponse_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (x *GetFileResponse) GetChunk() []byte {
	if x, ok := x.GetData().(*GetFileResponse_Chunk); ok {
		return x.Chunk
	}
	return nil
}

func (x *GetFileResponse) GetHeader() *FileHeader {
	if x, ok := x.GetData().(*GetFileResponse_Header); ok {
		return x.Header
	}
	return nil
}

type isGetFileResponse_Data interface {
	isGetFileResponse_Data()
}

type GetFileResponse_Chunk struct {
	Chunk []byte `protobuf:"bytes,1,opt,name=chunk,proto3,oneof"`
}

type GetFileResponse_Header struct {
	Header *FileHeader `protobuf:"bytes,2,opt,name=header,proto3,oneof"`
}

func (*GetFileResponse_Chunk) isGetFileResponse_Data() {}

func (*GetFileResponse_Header) isGetFileResponse_Data() {}

type SetFileV2Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Data:
	//
	//	*SetFileV2Request_Header
	//	*SetFileV2Request_Chunk
	Data isSetFileV2Request_Data `protobuf_oneof:"data"`
}

func (x *SetFileV2Request) Reset() {
	*x = SetFileV2Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_store_service_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetFileV2Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetFileV2Request) ProtoMessage() {}

func (x *SetFileV2Request) ProtoReflect() protoreflect.Message {
	mi := &file_store_service_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetFileV2Request.ProtoReflect.Descriptor instead.
func (*SetFileV2Request) Descriptor() ([]byte, []int) {
	return file_store_service_proto_rawDescGZIP(), []int{7}
}

func (m *SetFileV2Request) GetData() isSetFileV2Request_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (x *SetFileV2Request) GetHeader() *FileHeader {
	if x, ok := x.GetData().(*SetFileV2Request_Header); ok {
		return x.Header
	}
	return nil
}

func (x *SetFileV2Request) GetChunk() *DataChunk {
	if x, ok := x.GetData().(*SetFileV2Request_Chunk); ok {
		return x.Chunk
	}
	return nil
}

type isSetFileV2Request_Data interface {
	isSetFileV2Request_Data()
}

type SetFileV2Request_Header struct {
	Header *FileHeader `protobuf:"bytes,1,opt,name=header,proto3,oneof"`
}

type SetFileV2Request_Chunk struct {
	Chunk *DataChunk `protobuf:"bytes,2,opt,name=chunk,proto3,oneof"`
}

func (*SetFileV2Request_Header) isSetFileV2Request_Data() {}

func (*SetFileV2Request_Chunk) isSetFileV2Request_Data() {}

type SetFileV2Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SetFileV2Response) Reset() {
	*x = SetFileV2Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_store_service_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetFileV2Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetFileV2Response) ProtoMessage() {}

func (x *SetFileV2Response) ProtoReflect() protoreflect.Message {
	mi := &file_store_service_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetFileV2Response.ProtoReflect.Descriptor instead.
func (*SetFileV2Response) Descriptor() ([]byte, []int) {
	return file_store_service_proto_rawDescGZIP(), []int{8}
}

type GetFileV2Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Data:
	//
	//	*GetFileV2Request_Header
	//	*GetFileV2Request_Pos
	Data isGetFileV2Request_Data `protobuf_oneof:"data"`
}

func (x *GetFileV2Request) Reset() {
	*x = GetFileV2Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_store_service_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetFileV2Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFileV2Request) ProtoMessage() {}

func (x *GetFileV2Request) ProtoReflect() protoreflect.Message {
	mi := &file_store_service_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFileV2Request.ProtoReflect.Descriptor instead.
func (*GetFileV2Request) Descriptor() ([]byte, []int) {
	return file_store_service_proto_rawDescGZIP(), []int{9}
}

func (m *GetFileV2Request) GetData() isGetFileV2Request_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (x *GetFileV2Request) GetHeader() *FileHeader {
	if x, ok := x.GetData().(*GetFileV2Request_Header); ok {
		return x.Header
	}
	return nil
}

func (x *GetFileV2Request) GetPos() *Seek {
	if x, ok := x.GetData().(*GetFileV2Request_Pos); ok {
		return x.Pos
	}
	return nil
}

type isGetFileV2Request_Data interface {
	isGetFileV2Request_Data()
}

type GetFileV2Request_Header struct {
	Header *FileHeader `protobuf:"bytes,1,opt,name=header,proto3,oneof"`
}

type GetFileV2Request_Pos struct {
	Pos *Seek `protobuf:"bytes,2,opt,name=pos,proto3,oneof"`
}

func (*GetFileV2Request_Header) isGetFileV2Request_Data() {}

func (*GetFileV2Request_Pos) isGetFileV2Request_Data() {}

type GetFileV2Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Data:
	//
	//	*GetFileV2Response_Size
	//	*GetFileV2Response_Chunk
	Data isGetFileV2Response_Data `protobuf_oneof:"data"`
}

func (x *GetFileV2Response) Reset() {
	*x = GetFileV2Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_store_service_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetFileV2Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFileV2Response) ProtoMessage() {}

func (x *GetFileV2Response) ProtoReflect() protoreflect.Message {
	mi := &file_store_service_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFileV2Response.ProtoReflect.Descriptor instead.
func (*GetFileV2Response) Descriptor() ([]byte, []int) {
	return file_store_service_proto_rawDescGZIP(), []int{10}
}

func (m *GetFileV2Response) GetData() isGetFileV2Response_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (x *GetFileV2Response) GetSize() int64 {
	if x, ok := x.GetData().(*GetFileV2Response_Size); ok {
		return x.Size
	}
	return 0
}

func (x *GetFileV2Response) GetChunk() []byte {
	if x, ok := x.GetData().(*GetFileV2Response_Chunk); ok {
		return x.Chunk
	}
	return nil
}

type isGetFileV2Response_Data interface {
	isGetFileV2Response_Data()
}

type GetFileV2Response_Size struct {
	Size int64 `protobuf:"varint,1,opt,name=size,proto3,oneof"`
}

type GetFileV2Response_Chunk struct {
	Chunk []byte `protobuf:"bytes,2,opt,name=chunk,proto3,oneof"`
}

func (*GetFileV2Response_Size) isGetFileV2Response_Data() {}

func (*GetFileV2Response_Chunk) isGetFileV2Response_Data() {}

type GetKeysRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetKeysRequest) Reset() {
	*x = GetKeysRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_store_service_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetKeysRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetKeysRequest) ProtoMessage() {}

func (x *GetKeysRequest) ProtoReflect() protoreflect.Message {
	mi := &file_store_service_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetKeysRequest.ProtoReflect.Descriptor instead.
func (*GetKeysRequest) Descriptor() ([]byte, []int) {
	return file_store_service_proto_rawDescGZIP(), []int{11}
}

type GetKeysResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Keys []string `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`
}

func (x *GetKeysResponse) Reset() {
	*x = GetKeysResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_store_service_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetKeysResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetKeysResponse) ProtoMessage() {}

func (x *GetKeysResponse) ProtoReflect() protoreflect.Message {
	mi := &file_store_service_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetKeysResponse.ProtoReflect.Descriptor instead.
func (*GetKeysResponse) Descriptor() ([]byte, []int) {
	return file_store_service_proto_rawDescGZIP(), []int{12}
}

func (x *GetKeysResponse) GetKeys() []string {
	if x != nil {
		return x.Keys
	}
	return nil
}

type DeleteFileRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *DeleteFileRequest) Reset() {
	*x = DeleteFileRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_store_service_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFileRequest) ProtoMessage() {}

func (x *DeleteFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_store_service_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFileRequest.ProtoReflect.Descriptor instead.
func (*DeleteFileRequest) Descriptor() ([]byte, []int) {
	return file_store_service_proto_rawDescGZIP(), []int{13}
}

func (x *DeleteFileRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type DeleteFileResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteFileResponse) Reset() {
	*x = DeleteFileResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_store_service_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFileResponse) ProtoMessage() {}

func (x *DeleteFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_store_service_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFileResponse.ProtoReflect.Descriptor instead.
func (*DeleteFileResponse) Descriptor() ([]byte, []int) {
	return file_store_service_proto_rawDescGZIP(), []int{14}
}

type BeginTxRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsoLevel TxIsoLevel `protobuf:"varint,1,opt,name=isoLevel,proto3,enum=store.TxIsoLevel" json:"isoLevel,omitempty"`
}

func (x *BeginTxRequest) Reset() {
	*x = BeginTxRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_store_service_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BeginTxRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BeginTxRequest) ProtoMessage() {}

func (x *BeginTxRequest) ProtoReflect() protoreflect.Message {
	mi := &file_store_service_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BeginTxRequest.ProtoReflect.Descriptor instead.
func (*BeginTxRequest) Descriptor() ([]byte, []int) {
	return file_store_service_proto_rawDescGZIP(), []int{15}
}

func (x *BeginTxRequest) GetIsoLevel() TxIsoLevel {
	if x != nil {
		return x.IsoLevel
	}
	return TxIsoLevel_ISO_LEVEL_READ_UNCOMMITTED
}

type BeginTxResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *BeginTxResponse) Reset() {
	*x = BeginTxResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_store_service_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BeginTxResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BeginTxResponse) ProtoMessage() {}

func (x *BeginTxResponse) ProtoReflect() protoreflect.Message {
	mi := &file_store_service_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BeginTxResponse.ProtoReflect.Descriptor instead.
func (*BeginTxResponse) Descriptor() ([]byte, []int) {
	return file_store_service_proto_rawDescGZIP(), []int{16}
}

func (x *BeginTxResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type CommitTxRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CommitTxRequest) Reset() {
	*x = CommitTxRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_store_service_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommitTxRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitTxRequest) ProtoMessage() {}

func (x *CommitTxRequest) ProtoReflect() protoreflect.Message {
	mi := &file_store_service_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitTxRequest.ProtoReflect.Descriptor instead.
func (*CommitTxRequest) Descriptor() ([]byte, []int) {
	return file_store_service_proto_rawDescGZIP(), []int{17}
}

type CommitTxResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CommitTxResponse) Reset() {
	*x = CommitTxResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_store_service_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommitTxResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitTxResponse) ProtoMessage() {}

func (x *CommitTxResponse) ProtoReflect() protoreflect.Message {
	mi := &file_store_service_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitTxResponse.ProtoReflect.Descriptor instead.
func (*CommitTxResponse) Descriptor() ([]byte, []int) {
	return file_store_service_proto_rawDescGZIP(), []int{18}
}

type RollbackTxRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RollbackTxRequest) Reset() {
	*x = RollbackTxRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_store_service_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RollbackTxRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RollbackTxRequest) ProtoMessage() {}

func (x *RollbackTxRequest) ProtoReflect() protoreflect.Message {
	mi := &file_store_service_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RollbackTxRequest.ProtoReflect.Descriptor instead.
func (*RollbackTxRequest) Descriptor() ([]byte, []int) {
	return file_store_service_proto_rawDescGZIP(), []int{19}
}

type RollbackTxResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RollbackTxResponse) Reset() {
	*x = RollbackTxResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_store_service_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RollbackTxResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RollbackTxResponse) ProtoMessage() {}

func (x *RollbackTxResponse) ProtoReflect() protoreflect.Message {
	mi := &file_store_service_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RollbackTxResponse.ProtoReflect.Descriptor instead.
func (*RollbackTxResponse) Descriptor() ([]byte, []int) {
	return file_store_service_proto_rawDescGZIP(), []int{20}
}

var File_store_service_proto protoreflect.FileDescriptor

var file_store_service_proto_rawDesc = []byte{
	0x0a, 0x13, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x22, 0x36, 0x0a, 0x0a,
	0x46, 0x69, 0x6c, 0x65, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65,
	0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x16, 0x0a, 0x04,
	0x73, 0x69, 0x7a, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x42, 0x02, 0x18, 0x01, 0x52, 0x04,
	0x73, 0x69, 0x7a, 0x65, 0x22, 0x81, 0x01, 0x0a, 0x04, 0x53, 0x65, 0x65, 0x6b, 0x12, 0x16, 0x0a,
	0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x6f,
	0x66, 0x66, 0x73, 0x65, 0x74, 0x12, 0x27, 0x0a, 0x03, 0x64, 0x69, 0x72, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x15, 0x2e, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x2e, 0x53, 0x65, 0x65, 0x6b, 0x2e,
	0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x03, 0x64, 0x69, 0x72, 0x22, 0x38,
	0x0a, 0x09, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x0d, 0x0a, 0x09, 0x53,
	0x65, 0x65, 0x6b, 0x53, 0x74, 0x61, 0x72, 0x74, 0x10, 0x00, 0x12, 0x0f, 0x0a, 0x0b, 0x53, 0x65,
	0x65, 0x6b, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x10, 0x01, 0x12, 0x0b, 0x0a, 0x07, 0x53,
	0x65, 0x65, 0x6b, 0x45, 0x6e, 0x64, 0x10, 0x02, 0x22, 0x40, 0x0a, 0x09, 0x44, 0x61, 0x74, 0x61,
	0x43, 0x68, 0x75, 0x6e, 0x6b, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x68, 0x75, 0x6e, 0x6b, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x63, 0x68, 0x75, 0x6e, 0x6b, 0x12, 0x1d, 0x0a, 0x03, 0x70,
	0x6f, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x73, 0x74, 0x6f, 0x72, 0x65,
	0x2e, 0x53, 0x65, 0x65, 0x6b, 0x52, 0x03, 0x70, 0x6f, 0x73, 0x22, 0x5d, 0x0a, 0x0e, 0x53, 0x65,
	0x74, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2b, 0x0a, 0x06,
	0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x73,
	0x74, 0x6f, 0x72, 0x65, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x48,
	0x00, 0x52, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x16, 0x0a, 0x05, 0x63, 0x68, 0x75,
	0x6e, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x48, 0x00, 0x52, 0x05, 0x63, 0x68, 0x75, 0x6e,
	0x6b, 0x42, 0x06, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x11, 0x0a, 0x0f, 0x53, 0x65, 0x74,
	0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x22, 0x0a, 0x0e,
	0x47, 0x65, 0x74, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10,
	0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79,
	0x22, 0x5e, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x05, 0x63, 0x68, 0x75, 0x6e, 0x6b, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0c, 0x48, 0x00, 0x52, 0x05, 0x63, 0x68, 0x75, 0x6e, 0x6b, 0x12, 0x2b, 0x0a, 0x06, 0x68,
	0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x73, 0x74,
	0x6f, 0x72, 0x65, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x48, 0x00,
	0x52, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x42, 0x06, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61,
	0x22, 0x71, 0x0a, 0x10, 0x53, 0x65, 0x74, 0x46, 0x69, 0x6c, 0x65, 0x56, 0x32, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x2b, 0x0a, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x2e, 0x46, 0x69, 0x6c,
	0x65, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x48, 0x00, 0x52, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65,
	0x72, 0x12, 0x28, 0x0a, 0x05, 0x63, 0x68, 0x75, 0x6e, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x10, 0x2e, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x43, 0x68, 0x75,
	0x6e, 0x6b, 0x48, 0x00, 0x52, 0x05, 0x63, 0x68, 0x75, 0x6e, 0x6b, 0x42, 0x06, 0x0a, 0x04, 0x64,
	0x61, 0x74, 0x61, 0x22, 0x13, 0x0a, 0x11, 0x53, 0x65, 0x74, 0x46, 0x69, 0x6c, 0x65, 0x56, 0x32,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x68, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x46,
	0x69, 0x6c, 0x65, 0x56, 0x32, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2b, 0x0a, 0x06,
	0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x73,
	0x74, 0x6f, 0x72, 0x65, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x48,
	0x00, 0x52, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x1f, 0x0a, 0x03, 0x70, 0x6f, 0x73,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x2e, 0x53,
	0x65, 0x65, 0x6b, 0x48, 0x00, 0x52, 0x03, 0x70, 0x6f, 0x73, 0x42, 0x06, 0x0a, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x22, 0x49, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x46, 0x69, 0x6c, 0x65, 0x56, 0x32, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x48, 0x00, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x12, 0x16, 0x0a,
	0x05, 0x63, 0x68, 0x75, 0x6e, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x48, 0x00, 0x52, 0x05,
	0x63, 0x68, 0x75, 0x6e, 0x6b, 0x42, 0x06, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x10, 0x0a,
	0x0e, 0x47, 0x65, 0x74, 0x4b, 0x65, 0x79, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22,
	0x25, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x4b, 0x65, 0x79, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6b, 0x65, 0x79, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09,
	0x52, 0x04, 0x6b, 0x65, 0x79, 0x73, 0x22, 0x25, 0x0a, 0x11, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6b,
	0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x22, 0x14, 0x0a,
	0x12, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x3f, 0x0a, 0x0e, 0x42, 0x65, 0x67, 0x69, 0x6e, 0x54, 0x78, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2d, 0x0a, 0x08, 0x69, 0x73, 0x6f, 0x4c, 0x65, 0x76, 0x65,
	0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x11, 0x2e, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x2e,
	0x54, 0x78, 0x49, 0x73, 0x6f, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x52, 0x08, 0x69, 0x73, 0x6f, 0x4c,
	0x65, 0x76, 0x65, 0x6c, 0x22, 0x21, 0x0a, 0x0f, 0x42, 0x65, 0x67, 0x69, 0x6e, 0x54, 0x78, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x11, 0x0a, 0x0f, 0x43, 0x6f, 0x6d, 0x6d, 0x69,
	0x74, 0x54, 0x78, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x12, 0x0a, 0x10, 0x43, 0x6f,
	0x6d, 0x6d, 0x69, 0x74, 0x54, 0x78, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x13,
	0x0a, 0x11, 0x52, 0x6f, 0x6c, 0x6c, 0x62, 0x61, 0x63, 0x6b, 0x54, 0x78, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x22, 0x14, 0x0a, 0x12, 0x52, 0x6f, 0x6c, 0x6c, 0x62, 0x61, 0x63, 0x6b, 0x54,
	0x78, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2a, 0x20, 0x0a, 0x09, 0x43, 0x68, 0x75,
	0x6e, 0x6b, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x09, 0x0a, 0x05, 0x45, 0x4d, 0x50, 0x54, 0x59, 0x10,
	0x00, 0x12, 0x08, 0x0a, 0x03, 0x4d, 0x41, 0x58, 0x10, 0x80, 0x10, 0x2a, 0x85, 0x01, 0x0a, 0x0a,
	0x54, 0x78, 0x49, 0x73, 0x6f, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x12, 0x1e, 0x0a, 0x1a, 0x49, 0x53,
	0x4f, 0x5f, 0x4c, 0x45, 0x56, 0x45, 0x4c, 0x5f, 0x52, 0x45, 0x41, 0x44, 0x5f, 0x55, 0x4e, 0x43,
	0x4f, 0x4d, 0x4d, 0x49, 0x54, 0x54, 0x45, 0x44, 0x10, 0x00, 0x12, 0x1c, 0x0a, 0x18, 0x49, 0x53,
	0x4f, 0x5f, 0x4c, 0x45, 0x56, 0x45, 0x4c, 0x5f, 0x52, 0x45, 0x41, 0x44, 0x5f, 0x43, 0x4f, 0x4d,
	0x4d, 0x49, 0x54, 0x54, 0x45, 0x44, 0x10, 0x01, 0x12, 0x1d, 0x0a, 0x19, 0x49, 0x53, 0x4f, 0x5f,
	0x4c, 0x45, 0x56, 0x45, 0x4c, 0x5f, 0x52, 0x45, 0x50, 0x45, 0x41, 0x54, 0x41, 0x42, 0x4c, 0x45,
	0x5f, 0x52, 0x45, 0x41, 0x44, 0x10, 0x02, 0x12, 0x1a, 0x0a, 0x16, 0x49, 0x53, 0x4f, 0x5f, 0x4c,
	0x45, 0x56, 0x45, 0x4c, 0x5f, 0x53, 0x45, 0x52, 0x49, 0x41, 0x4c, 0x49, 0x5a, 0x41, 0x42, 0x4c,
	0x45, 0x10, 0x03, 0x32, 0xd0, 0x04, 0x0a, 0x07, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x56, 0x31, 0x12,
	0x3c, 0x0a, 0x07, 0x53, 0x65, 0x74, 0x46, 0x69, 0x6c, 0x65, 0x12, 0x15, 0x2e, 0x73, 0x74, 0x6f,
	0x72, 0x65, 0x2e, 0x53, 0x65, 0x74, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x16, 0x2e, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x2e, 0x53, 0x65, 0x74, 0x46, 0x69, 0x6c,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x28, 0x01, 0x12, 0x3c, 0x0a,
	0x07, 0x47, 0x65, 0x74, 0x46, 0x69, 0x6c, 0x65, 0x12, 0x15, 0x2e, 0x73, 0x74, 0x6f, 0x72, 0x65,
	0x2e, 0x47, 0x65, 0x74, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x16, 0x2e, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x46, 0x69, 0x6c, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x30, 0x01, 0x12, 0x42, 0x0a, 0x09, 0x53,
	0x65, 0x74, 0x46, 0x69, 0x6c, 0x65, 0x56, 0x32, 0x12, 0x17, 0x2e, 0x73, 0x74, 0x6f, 0x72, 0x65,
	0x2e, 0x53, 0x65, 0x74, 0x46, 0x69, 0x6c, 0x65, 0x56, 0x32, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x18, 0x2e, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x2e, 0x53, 0x65, 0x74, 0x46, 0x69, 0x6c,
	0x65, 0x56, 0x32, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x28, 0x01, 0x12,
	0x44, 0x0a, 0x09, 0x47, 0x65, 0x74, 0x46, 0x69, 0x6c, 0x65, 0x56, 0x32, 0x12, 0x17, 0x2e, 0x73,
	0x74, 0x6f, 0x72, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x46, 0x69, 0x6c, 0x65, 0x56, 0x32, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x2e, 0x47, 0x65,
	0x74, 0x46, 0x69, 0x6c, 0x65, 0x56, 0x32, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x28, 0x01, 0x30, 0x01, 0x12, 0x3a, 0x0a, 0x07, 0x47, 0x65, 0x74, 0x4b, 0x65, 0x79, 0x73,
	0x12, 0x15, 0x2e, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x4b, 0x65, 0x79, 0x73,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x2e,
	0x47, 0x65, 0x74, 0x4b, 0x65, 0x79, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x12, 0x43, 0x0a, 0x0a, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x46, 0x69, 0x6c, 0x65, 0x12,
	0x18, 0x2e, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x46, 0x69,
	0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x73, 0x74, 0x6f, 0x72,
	0x65, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x3a, 0x0a, 0x07, 0x42, 0x65, 0x67, 0x69, 0x6e, 0x54,
	0x78, 0x12, 0x15, 0x2e, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x2e, 0x42, 0x65, 0x67, 0x69, 0x6e, 0x54,
	0x78, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x73, 0x74, 0x6f, 0x72, 0x65,
	0x2e, 0x42, 0x65, 0x67, 0x69, 0x6e, 0x54, 0x78, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x12, 0x3d, 0x0a, 0x08, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x54, 0x78, 0x12, 0x16,
	0x2e, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x54, 0x78, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x2e, 0x43,
	0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x54, 0x78, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x12, 0x43, 0x0a, 0x0a, 0x52, 0x6f, 0x6c, 0x6c, 0x62, 0x61, 0x63, 0x6b, 0x54, 0x78, 0x12,
	0x18, 0x2e, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x2e, 0x52, 0x6f, 0x6c, 0x6c, 0x62, 0x61, 0x63, 0x6b,
	0x54, 0x78, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x73, 0x74, 0x6f, 0x72,
	0x65, 0x2e, 0x52, 0x6f, 0x6c, 0x6c, 0x62, 0x61, 0x63, 0x6b, 0x54, 0x78, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x13, 0x5a, 0x11, 0x66, 0x73, 0x5f, 0x66, 0x62, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_store_service_proto_rawDescOnce sync.Once
	file_store_service_proto_rawDescData = file_store_service_proto_rawDesc
)

func file_store_service_proto_rawDescGZIP() []byte {
	file_store_service_proto_rawDescOnce.Do(func() {
		file_store_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_store_service_proto_rawDescData)
	})
	return file_store_service_proto_rawDescData
}

var file_store_service_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_store_service_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_store_service_proto_goTypes = []interface{}{
	(ChunkSize)(0),             // 0: store.ChunkSize
	(TxIsoLevel)(0),            // 1: store.TxIsoLevel
	(Seek_Direction)(0),        // 2: store.Seek.Direction
	(*FileHeader)(nil),         // 3: store.FileHeader
	(*Seek)(nil),               // 4: store.Seek
	(*DataChunk)(nil),          // 5: store.DataChunk
	(*SetFileRequest)(nil),     // 6: store.SetFileRequest
	(*SetFileResponse)(nil),    // 7: store.SetFileResponse
	(*GetFileRequest)(nil),     // 8: store.GetFileRequest
	(*GetFileResponse)(nil),    // 9: store.GetFileResponse
	(*SetFileV2Request)(nil),   // 10: store.SetFileV2Request
	(*SetFileV2Response)(nil),  // 11: store.SetFileV2Response
	(*GetFileV2Request)(nil),   // 12: store.GetFileV2Request
	(*GetFileV2Response)(nil),  // 13: store.GetFileV2Response
	(*GetKeysRequest)(nil),     // 14: store.GetKeysRequest
	(*GetKeysResponse)(nil),    // 15: store.GetKeysResponse
	(*DeleteFileRequest)(nil),  // 16: store.DeleteFileRequest
	(*DeleteFileResponse)(nil), // 17: store.DeleteFileResponse
	(*BeginTxRequest)(nil),     // 18: store.BeginTxRequest
	(*BeginTxResponse)(nil),    // 19: store.BeginTxResponse
	(*CommitTxRequest)(nil),    // 20: store.CommitTxRequest
	(*CommitTxResponse)(nil),   // 21: store.CommitTxResponse
	(*RollbackTxRequest)(nil),  // 22: store.RollbackTxRequest
	(*RollbackTxResponse)(nil), // 23: store.RollbackTxResponse
}
var file_store_service_proto_depIdxs = []int32{
	2,  // 0: store.Seek.dir:type_name -> store.Seek.Direction
	4,  // 1: store.DataChunk.pos:type_name -> store.Seek
	3,  // 2: store.SetFileRequest.header:type_name -> store.FileHeader
	3,  // 3: store.GetFileResponse.header:type_name -> store.FileHeader
	3,  // 4: store.SetFileV2Request.header:type_name -> store.FileHeader
	5,  // 5: store.SetFileV2Request.chunk:type_name -> store.DataChunk
	3,  // 6: store.GetFileV2Request.header:type_name -> store.FileHeader
	4,  // 7: store.GetFileV2Request.pos:type_name -> store.Seek
	1,  // 8: store.BeginTxRequest.isoLevel:type_name -> store.TxIsoLevel
	6,  // 9: store.StoreV1.SetFile:input_type -> store.SetFileRequest
	8,  // 10: store.StoreV1.GetFile:input_type -> store.GetFileRequest
	10, // 11: store.StoreV1.SetFileV2:input_type -> store.SetFileV2Request
	12, // 12: store.StoreV1.GetFileV2:input_type -> store.GetFileV2Request
	14, // 13: store.StoreV1.GetKeys:input_type -> store.GetKeysRequest
	16, // 14: store.StoreV1.DeleteFile:input_type -> store.DeleteFileRequest
	18, // 15: store.StoreV1.BeginTx:input_type -> store.BeginTxRequest
	20, // 16: store.StoreV1.CommitTx:input_type -> store.CommitTxRequest
	22, // 17: store.StoreV1.RollbackTx:input_type -> store.RollbackTxRequest
	7,  // 18: store.StoreV1.SetFile:output_type -> store.SetFileResponse
	9,  // 19: store.StoreV1.GetFile:output_type -> store.GetFileResponse
	11, // 20: store.StoreV1.SetFileV2:output_type -> store.SetFileV2Response
	13, // 21: store.StoreV1.GetFileV2:output_type -> store.GetFileV2Response
	15, // 22: store.StoreV1.GetKeys:output_type -> store.GetKeysResponse
	17, // 23: store.StoreV1.DeleteFile:output_type -> store.DeleteFileResponse
	19, // 24: store.StoreV1.BeginTx:output_type -> store.BeginTxResponse
	21, // 25: store.StoreV1.CommitTx:output_type -> store.CommitTxResponse
	23, // 26: store.StoreV1.RollbackTx:output_type -> store.RollbackTxResponse
	18, // [18:27] is the sub-list for method output_type
	9,  // [9:18] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_store_service_proto_init() }
func file_store_service_proto_init() {
	if File_store_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_store_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FileHeader); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_store_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Seek); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_store_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DataChunk); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_store_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetFileRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_store_service_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetFileResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_store_service_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetFileRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_store_service_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetFileResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_store_service_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetFileV2Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_store_service_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetFileV2Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_store_service_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetFileV2Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_store_service_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetFileV2Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_store_service_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetKeysRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_store_service_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetKeysResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_store_service_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteFileRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_store_service_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteFileResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_store_service_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BeginTxRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_store_service_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BeginTxResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_store_service_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommitTxRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_store_service_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommitTxResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_store_service_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RollbackTxRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_store_service_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RollbackTxResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_store_service_proto_msgTypes[3].OneofWrappers = []interface{}{
		(*SetFileRequest_Header)(nil),
		(*SetFileRequest_Chunk)(nil),
	}
	file_store_service_proto_msgTypes[6].OneofWrappers = []interface{}{
		(*GetFileResponse_Chunk)(nil),
		(*GetFileResponse_Header)(nil),
	}
	file_store_service_proto_msgTypes[7].OneofWrappers = []interface{}{
		(*SetFileV2Request_Header)(nil),
		(*SetFileV2Request_Chunk)(nil),
	}
	file_store_service_proto_msgTypes[9].OneofWrappers = []interface{}{
		(*GetFileV2Request_Header)(nil),
		(*GetFileV2Request_Pos)(nil),
	}
	file_store_service_proto_msgTypes[10].OneofWrappers = []interface{}{
		(*GetFileV2Response_Size)(nil),
		(*GetFileV2Response_Chunk)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_store_service_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_store_service_proto_goTypes,
		DependencyIndexes: file_store_service_proto_depIdxs,
		EnumInfos:         file_store_service_proto_enumTypes,
		MessageInfos:      file_store_service_proto_msgTypes,
	}.Build()
	File_store_service_proto = out.File
	file_store_service_proto_rawDesc = nil
	file_store_service_proto_goTypes = nil
	file_store_service_proto_depIdxs = nil
}
