// Code generated by MockGen. DO NOT EDIT.
// Source: repository.go
//
// Generated by this command:
//
//	mockgen -source repository.go -package mocks -destination mocks/mocks.go -typed true
//
// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	os "os"
	reflect "reflect"

	disk "github.com/shirou/gopsutil/disk"
	gomock "go.uber.org/mock/gomock"
)

// MockosAdapter is a mock of osAdapter interface.
type MockosAdapter struct {
	ctrl     *gomock.Controller
	recorder *MockosAdapterMockRecorder
}

// MockosAdapterMockRecorder is the mock recorder for MockosAdapter.
type MockosAdapterMockRecorder struct {
	mock *MockosAdapter
}

// NewMockosAdapter creates a new mock instance.
func NewMockosAdapter(ctrl *gomock.Controller) *MockosAdapter {
	mock := &MockosAdapter{ctrl: ctrl}
	mock.recorder = &MockosAdapterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockosAdapter) EXPECT() *MockosAdapterMockRecorder {
	return m.recorder
}

// MkdirAll mocks base method.
func (m *MockosAdapter) MkdirAll(ctx context.Context, path string, perm os.FileMode) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MkdirAll", ctx, path, perm)
	ret0, _ := ret[0].(error)
	return ret0
}

// MkdirAll indicates an expected call of MkdirAll.
func (mr *MockosAdapterMockRecorder) MkdirAll(ctx, path, perm any) *osAdapterMkdirAllCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MkdirAll", reflect.TypeOf((*MockosAdapter)(nil).MkdirAll), ctx, path, perm)
	return &osAdapterMkdirAllCall{Call: call}
}

// osAdapterMkdirAllCall wrap *gomock.Call
type osAdapterMkdirAllCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *osAdapterMkdirAllCall) Return(arg0 error) *osAdapterMkdirAllCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *osAdapterMkdirAllCall) Do(f func(context.Context, string, os.FileMode) error) *osAdapterMkdirAllCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *osAdapterMkdirAllCall) DoAndReturn(f func(context.Context, string, os.FileMode) error) *osAdapterMkdirAllCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ReadDir mocks base method.
func (m *MockosAdapter) ReadDir(ctx context.Context, name string) ([]os.DirEntry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadDir", ctx, name)
	ret0, _ := ret[0].([]os.DirEntry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadDir indicates an expected call of ReadDir.
func (mr *MockosAdapterMockRecorder) ReadDir(ctx, name any) *osAdapterReadDirCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadDir", reflect.TypeOf((*MockosAdapter)(nil).ReadDir), ctx, name)
	return &osAdapterReadDirCall{Call: call}
}

// osAdapterReadDirCall wrap *gomock.Call
type osAdapterReadDirCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *osAdapterReadDirCall) Return(arg0 []os.DirEntry, arg1 error) *osAdapterReadDirCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *osAdapterReadDirCall) Do(f func(context.Context, string) ([]os.DirEntry, error)) *osAdapterReadDirCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *osAdapterReadDirCall) DoAndReturn(f func(context.Context, string) ([]os.DirEntry, error)) *osAdapterReadDirCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Usage mocks base method.
func (m *MockosAdapter) Usage(ctx context.Context, path string) (*disk.UsageStat, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Usage", ctx, path)
	ret0, _ := ret[0].(*disk.UsageStat)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Usage indicates an expected call of Usage.
func (mr *MockosAdapterMockRecorder) Usage(ctx, path any) *osAdapterUsageCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Usage", reflect.TypeOf((*MockosAdapter)(nil).Usage), ctx, path)
	return &osAdapterUsageCall{Call: call}
}

// osAdapterUsageCall wrap *gomock.Call
type osAdapterUsageCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *osAdapterUsageCall) Return(arg0 *disk.UsageStat, arg1 error) *osAdapterUsageCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *osAdapterUsageCall) Do(f func(context.Context, string) (*disk.UsageStat, error)) *osAdapterUsageCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *osAdapterUsageCall) DoAndReturn(f func(context.Context, string) (*disk.UsageStat, error)) *osAdapterUsageCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
