// Code generated by MockGen. DO NOT EDIT.
// Source: repository.go
//
// Generated by this command:
//
//	mockgen -source repository.go -package mocks -destination mocks/mocks.go -typed true
//
// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	os "os"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockosAdapter is a mock of osAdapter interface.
type MockosAdapter struct {
	ctrl     *gomock.Controller
	recorder *MockosAdapterMockRecorder
}

// MockosAdapterMockRecorder is the mock recorder for MockosAdapter.
type MockosAdapterMockRecorder struct {
	mock *MockosAdapter
}

// NewMockosAdapter creates a new mock instance.
func NewMockosAdapter(ctrl *gomock.Controller) *MockosAdapter {
	mock := &MockosAdapter{ctrl: ctrl}
	mock.recorder = &MockosAdapterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockosAdapter) EXPECT() *MockosAdapterMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockosAdapter) Create(ctx context.Context, path string) (*os.File, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, path)
	ret0, _ := ret[0].(*os.File)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockosAdapterMockRecorder) Create(ctx, path any) *osAdapterCreateCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockosAdapter)(nil).Create), ctx, path)
	return &osAdapterCreateCall{Call: call}
}

// osAdapterCreateCall wrap *gomock.Call
type osAdapterCreateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *osAdapterCreateCall) Return(arg0 *os.File, arg1 error) *osAdapterCreateCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *osAdapterCreateCall) Do(f func(context.Context, string) (*os.File, error)) *osAdapterCreateCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *osAdapterCreateCall) DoAndReturn(f func(context.Context, string) (*os.File, error)) *osAdapterCreateCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Open mocks base method.
func (m *MockosAdapter) Open(ctx context.Context, path string) (*os.File, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Open", ctx, path)
	ret0, _ := ret[0].(*os.File)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Open indicates an expected call of Open.
func (mr *MockosAdapterMockRecorder) Open(ctx, path any) *osAdapterOpenCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Open", reflect.TypeOf((*MockosAdapter)(nil).Open), ctx, path)
	return &osAdapterOpenCall{Call: call}
}

// osAdapterOpenCall wrap *gomock.Call
type osAdapterOpenCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *osAdapterOpenCall) Return(arg0 *os.File, arg1 error) *osAdapterOpenCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *osAdapterOpenCall) Do(f func(context.Context, string) (*os.File, error)) *osAdapterOpenCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *osAdapterOpenCall) DoAndReturn(f func(context.Context, string) (*os.File, error)) *osAdapterOpenCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Remove mocks base method.
func (m *MockosAdapter) Remove(ctx context.Context, path string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Remove", ctx, path)
	ret0, _ := ret[0].(error)
	return ret0
}

// Remove indicates an expected call of Remove.
func (mr *MockosAdapterMockRecorder) Remove(ctx, path any) *osAdapterRemoveCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Remove", reflect.TypeOf((*MockosAdapter)(nil).Remove), ctx, path)
	return &osAdapterRemoveCall{Call: call}
}

// osAdapterRemoveCall wrap *gomock.Call
type osAdapterRemoveCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *osAdapterRemoveCall) Return(arg0 error) *osAdapterRemoveCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *osAdapterRemoveCall) Do(f func(context.Context, string) error) *osAdapterRemoveCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *osAdapterRemoveCall) DoAndReturn(f func(context.Context, string) error) *osAdapterRemoveCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
