// Code generated by MockGen. DO NOT EDIT.
// Source: ../../model/io.go
//
// Generated by this command:
//
//	mockgen -source ../../model/io.go -package mocks -destination mocks/mocks_io.go -typed true
//
// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockReadWriteSeekCloser is a mock of ReadWriteSeekCloser interface.
type MockReadWriteSeekCloser struct {
	ctrl     *gomock.Controller
	recorder *MockReadWriteSeekCloserMockRecorder
}

// MockReadWriteSeekCloserMockRecorder is the mock recorder for MockReadWriteSeekCloser.
type MockReadWriteSeekCloserMockRecorder struct {
	mock *MockReadWriteSeekCloser
}

// NewMockReadWriteSeekCloser creates a new mock instance.
func NewMockReadWriteSeekCloser(ctrl *gomock.Controller) *MockReadWriteSeekCloser {
	mock := &MockReadWriteSeekCloser{ctrl: ctrl}
	mock.recorder = &MockReadWriteSeekCloserMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReadWriteSeekCloser) EXPECT() *MockReadWriteSeekCloserMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockReadWriteSeekCloser) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockReadWriteSeekCloserMockRecorder) Close() *ReadWriteSeekCloserCloseCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockReadWriteSeekCloser)(nil).Close))
	return &ReadWriteSeekCloserCloseCall{Call: call}
}

// ReadWriteSeekCloserCloseCall wrap *gomock.Call
type ReadWriteSeekCloserCloseCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *ReadWriteSeekCloserCloseCall) Return(arg0 error) *ReadWriteSeekCloserCloseCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *ReadWriteSeekCloserCloseCall) Do(f func() error) *ReadWriteSeekCloserCloseCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *ReadWriteSeekCloserCloseCall) DoAndReturn(f func() error) *ReadWriteSeekCloserCloseCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Read mocks base method.
func (m *MockReadWriteSeekCloser) Read(p []byte) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Read", p)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Read indicates an expected call of Read.
func (mr *MockReadWriteSeekCloserMockRecorder) Read(p any) *ReadWriteSeekCloserReadCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Read", reflect.TypeOf((*MockReadWriteSeekCloser)(nil).Read), p)
	return &ReadWriteSeekCloserReadCall{Call: call}
}

// ReadWriteSeekCloserReadCall wrap *gomock.Call
type ReadWriteSeekCloserReadCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *ReadWriteSeekCloserReadCall) Return(n int, err error) *ReadWriteSeekCloserReadCall {
	c.Call = c.Call.Return(n, err)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *ReadWriteSeekCloserReadCall) Do(f func([]byte) (int, error)) *ReadWriteSeekCloserReadCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *ReadWriteSeekCloserReadCall) DoAndReturn(f func([]byte) (int, error)) *ReadWriteSeekCloserReadCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ReadAt mocks base method.
func (m *MockReadWriteSeekCloser) ReadAt(p []byte, off int64) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadAt", p, off)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadAt indicates an expected call of ReadAt.
func (mr *MockReadWriteSeekCloserMockRecorder) ReadAt(p, off any) *ReadWriteSeekCloserReadAtCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadAt", reflect.TypeOf((*MockReadWriteSeekCloser)(nil).ReadAt), p, off)
	return &ReadWriteSeekCloserReadAtCall{Call: call}
}

// ReadWriteSeekCloserReadAtCall wrap *gomock.Call
type ReadWriteSeekCloserReadAtCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *ReadWriteSeekCloserReadAtCall) Return(n int, err error) *ReadWriteSeekCloserReadAtCall {
	c.Call = c.Call.Return(n, err)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *ReadWriteSeekCloserReadAtCall) Do(f func([]byte, int64) (int, error)) *ReadWriteSeekCloserReadAtCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *ReadWriteSeekCloserReadAtCall) DoAndReturn(f func([]byte, int64) (int, error)) *ReadWriteSeekCloserReadAtCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Seek mocks base method.
func (m *MockReadWriteSeekCloser) Seek(offset int64, whence int) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Seek", offset, whence)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Seek indicates an expected call of Seek.
func (mr *MockReadWriteSeekCloserMockRecorder) Seek(offset, whence any) *ReadWriteSeekCloserSeekCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Seek", reflect.TypeOf((*MockReadWriteSeekCloser)(nil).Seek), offset, whence)
	return &ReadWriteSeekCloserSeekCall{Call: call}
}

// ReadWriteSeekCloserSeekCall wrap *gomock.Call
type ReadWriteSeekCloserSeekCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *ReadWriteSeekCloserSeekCall) Return(arg0 int64, arg1 error) *ReadWriteSeekCloserSeekCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *ReadWriteSeekCloserSeekCall) Do(f func(int64, int) (int64, error)) *ReadWriteSeekCloserSeekCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *ReadWriteSeekCloserSeekCall) DoAndReturn(f func(int64, int) (int64, error)) *ReadWriteSeekCloserSeekCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Write mocks base method.
func (m *MockReadWriteSeekCloser) Write(p []byte) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Write", p)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Write indicates an expected call of Write.
func (mr *MockReadWriteSeekCloserMockRecorder) Write(p any) *ReadWriteSeekCloserWriteCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Write", reflect.TypeOf((*MockReadWriteSeekCloser)(nil).Write), p)
	return &ReadWriteSeekCloserWriteCall{Call: call}
}

// ReadWriteSeekCloserWriteCall wrap *gomock.Call
type ReadWriteSeekCloserWriteCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *ReadWriteSeekCloserWriteCall) Return(n int, err error) *ReadWriteSeekCloserWriteCall {
	c.Call = c.Call.Return(n, err)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *ReadWriteSeekCloserWriteCall) Do(f func([]byte) (int, error)) *ReadWriteSeekCloserWriteCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *ReadWriteSeekCloserWriteCall) DoAndReturn(f func([]byte) (int, error)) *ReadWriteSeekCloserWriteCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockReadSeekCloser is a mock of ReadSeekCloser interface.
type MockReadSeekCloser struct {
	ctrl     *gomock.Controller
	recorder *MockReadSeekCloserMockRecorder
}

// MockReadSeekCloserMockRecorder is the mock recorder for MockReadSeekCloser.
type MockReadSeekCloserMockRecorder struct {
	mock *MockReadSeekCloser
}

// NewMockReadSeekCloser creates a new mock instance.
func NewMockReadSeekCloser(ctrl *gomock.Controller) *MockReadSeekCloser {
	mock := &MockReadSeekCloser{ctrl: ctrl}
	mock.recorder = &MockReadSeekCloserMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReadSeekCloser) EXPECT() *MockReadSeekCloserMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockReadSeekCloser) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockReadSeekCloserMockRecorder) Close() *ReadSeekCloserCloseCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockReadSeekCloser)(nil).Close))
	return &ReadSeekCloserCloseCall{Call: call}
}

// ReadSeekCloserCloseCall wrap *gomock.Call
type ReadSeekCloserCloseCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *ReadSeekCloserCloseCall) Return(arg0 error) *ReadSeekCloserCloseCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *ReadSeekCloserCloseCall) Do(f func() error) *ReadSeekCloserCloseCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *ReadSeekCloserCloseCall) DoAndReturn(f func() error) *ReadSeekCloserCloseCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Read mocks base method.
func (m *MockReadSeekCloser) Read(p []byte) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Read", p)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Read indicates an expected call of Read.
func (mr *MockReadSeekCloserMockRecorder) Read(p any) *ReadSeekCloserReadCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Read", reflect.TypeOf((*MockReadSeekCloser)(nil).Read), p)
	return &ReadSeekCloserReadCall{Call: call}
}

// ReadSeekCloserReadCall wrap *gomock.Call
type ReadSeekCloserReadCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *ReadSeekCloserReadCall) Return(n int, err error) *ReadSeekCloserReadCall {
	c.Call = c.Call.Return(n, err)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *ReadSeekCloserReadCall) Do(f func([]byte) (int, error)) *ReadSeekCloserReadCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *ReadSeekCloserReadCall) DoAndReturn(f func([]byte) (int, error)) *ReadSeekCloserReadCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ReadAt mocks base method.
func (m *MockReadSeekCloser) ReadAt(p []byte, off int64) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadAt", p, off)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadAt indicates an expected call of ReadAt.
func (mr *MockReadSeekCloserMockRecorder) ReadAt(p, off any) *ReadSeekCloserReadAtCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadAt", reflect.TypeOf((*MockReadSeekCloser)(nil).ReadAt), p, off)
	return &ReadSeekCloserReadAtCall{Call: call}
}

// ReadSeekCloserReadAtCall wrap *gomock.Call
type ReadSeekCloserReadAtCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *ReadSeekCloserReadAtCall) Return(n int, err error) *ReadSeekCloserReadAtCall {
	c.Call = c.Call.Return(n, err)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *ReadSeekCloserReadAtCall) Do(f func([]byte, int64) (int, error)) *ReadSeekCloserReadAtCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *ReadSeekCloserReadAtCall) DoAndReturn(f func([]byte, int64) (int, error)) *ReadSeekCloserReadAtCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Seek mocks base method.
func (m *MockReadSeekCloser) Seek(offset int64, whence int) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Seek", offset, whence)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Seek indicates an expected call of Seek.
func (mr *MockReadSeekCloserMockRecorder) Seek(offset, whence any) *ReadSeekCloserSeekCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Seek", reflect.TypeOf((*MockReadSeekCloser)(nil).Seek), offset, whence)
	return &ReadSeekCloserSeekCall{Call: call}
}

// ReadSeekCloserSeekCall wrap *gomock.Call
type ReadSeekCloserSeekCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *ReadSeekCloserSeekCall) Return(arg0 int64, arg1 error) *ReadSeekCloserSeekCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *ReadSeekCloserSeekCall) Do(f func(int64, int) (int64, error)) *ReadSeekCloserSeekCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *ReadSeekCloserSeekCall) DoAndReturn(f func(int64, int) (int64, error)) *ReadSeekCloserSeekCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
