// Code generated by MockGen. DO NOT EDIT.
// Source: reader.go
//
// Generated by this command:
//
//	mockgen -source reader.go -destination mocks/mocks.go -typed true
//
// Package mock_streamreader is a generated GoMock package.
package mock_streamreader

import (
	reflect "reflect"

	streamreader "github.com/glebziz/fs_db/internal/utils/grpc/streamreader"
	gomock "go.uber.org/mock/gomock"
)

// MockRequest is a mock of Request interface.
type MockRequest struct {
	ctrl     *gomock.Controller
	recorder *MockRequestMockRecorder
}

// MockRequestMockRecorder is the mock recorder for MockRequest.
type MockRequestMockRecorder struct {
	mock *MockRequest
}

// NewMockRequest creates a new mock instance.
func NewMockRequest(ctrl *gomock.Controller) *MockRequest {
	mock := &MockRequest{ctrl: ctrl}
	mock.recorder = &MockRequestMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRequest) EXPECT() *MockRequestMockRecorder {
	return m.recorder
}

// GetChunk mocks base method.
func (m *MockRequest) GetChunk() []byte {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetChunk")
	ret0, _ := ret[0].([]byte)
	return ret0
}

// GetChunk indicates an expected call of GetChunk.
func (mr *MockRequestMockRecorder) GetChunk() *RequestGetChunkCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetChunk", reflect.TypeOf((*MockRequest)(nil).GetChunk))
	return &RequestGetChunkCall{Call: call}
}

// RequestGetChunkCall wrap *gomock.Call
type RequestGetChunkCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *RequestGetChunkCall) Return(arg0 []byte) *RequestGetChunkCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *RequestGetChunkCall) Do(f func() []byte) *RequestGetChunkCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *RequestGetChunkCall) DoAndReturn(f func() []byte) *RequestGetChunkCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockStream is a mock of Stream interface.
type MockStream[T streamreader.Request] struct {
	ctrl     *gomock.Controller
	recorder *MockStreamMockRecorder[T]
}

// MockStreamMockRecorder is the mock recorder for MockStream.
type MockStreamMockRecorder[T streamreader.Request] struct {
	mock *MockStream[T]
}

// NewMockStream creates a new mock instance.
func NewMockStream[T streamreader.Request](ctrl *gomock.Controller) *MockStream[T] {
	mock := &MockStream[T]{ctrl: ctrl}
	mock.recorder = &MockStreamMockRecorder[T]{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStream[T]) EXPECT() *MockStreamMockRecorder[T] {
	return m.recorder
}

// Recv mocks base method.
func (m *MockStream[T]) Recv() (T, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Recv")
	ret0, _ := ret[0].(T)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Recv indicates an expected call of Recv.
func (mr *MockStreamMockRecorder[T]) Recv() *StreamRecvCall[T] {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Recv", reflect.TypeOf((*MockStream[T])(nil).Recv))
	return &StreamRecvCall[T]{Call: call}
}

// StreamRecvCall wrap *gomock.Call
type StreamRecvCall[T streamreader.Request] struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *StreamRecvCall[T]) Return(arg0 T, arg1 error) *StreamRecvCall[T] {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *StreamRecvCall[T]) Do(f func() (T, error)) *StreamRecvCall[T] {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *StreamRecvCall[T]) DoAndReturn(f func() (T, error)) *StreamRecvCall[T] {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
