// Code generated by MockGen. DO NOT EDIT.
// Source: reader.go
//
// Generated by this command:
//
//	mockgen -source reader.go -destination mocks/mocks.go -typed true
//
// Package mock_dstreamreader is a generated GoMock package.
package mock_dstreamreader

import (
	reflect "reflect"

	dstreamreader "github.com/glebziz/fs_db/internal/utils/grpc/dstreamreader"
	gomock "go.uber.org/mock/gomock"
	proto "google.golang.org/protobuf/proto"
)

// MockResponse is a mock of Response interface.
type MockResponse struct {
	ctrl     *gomock.Controller
	recorder *MockResponseMockRecorder
}

// MockResponseMockRecorder is the mock recorder for MockResponse.
type MockResponseMockRecorder struct {
	mock *MockResponse
}

// NewMockResponse creates a new mock instance.
func NewMockResponse(ctrl *gomock.Controller) *MockResponse {
	mock := &MockResponse{ctrl: ctrl}
	mock.recorder = &MockResponseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockResponse) EXPECT() *MockResponseMockRecorder {
	return m.recorder
}

// GetChunk mocks base method.
func (m *MockResponse) GetChunk() []byte {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetChunk")
	ret0, _ := ret[0].([]byte)
	return ret0
}

// GetChunk indicates an expected call of GetChunk.
func (mr *MockResponseMockRecorder) GetChunk() *ResponseGetChunkCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetChunk", reflect.TypeOf((*MockResponse)(nil).GetChunk))
	return &ResponseGetChunkCall{Call: call}
}

// ResponseGetChunkCall wrap *gomock.Call
type ResponseGetChunkCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *ResponseGetChunkCall) Return(arg0 []byte) *ResponseGetChunkCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *ResponseGetChunkCall) Do(f func() []byte) *ResponseGetChunkCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *ResponseGetChunkCall) DoAndReturn(f func() []byte) *ResponseGetChunkCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockStream is a mock of Stream interface.
type MockStream[Req proto.Message, Resp dstreamreader.Response] struct {
	ctrl     *gomock.Controller
	recorder *MockStreamMockRecorder[Req, Resp]
}

// MockStreamMockRecorder is the mock recorder for MockStream.
type MockStreamMockRecorder[Req proto.Message, Resp dstreamreader.Response] struct {
	mock *MockStream[Req, Resp]
}

// NewMockStream creates a new mock instance.
func NewMockStream[Req proto.Message, Resp dstreamreader.Response](ctrl *gomock.Controller) *MockStream[Req, Resp] {
	mock := &MockStream[Req, Resp]{ctrl: ctrl}
	mock.recorder = &MockStreamMockRecorder[Req, Resp]{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStream[Req, Resp]) EXPECT() *MockStreamMockRecorder[Req, Resp] {
	return m.recorder
}

// CloseSend mocks base method.
func (m *MockStream[Req, Resp]) CloseSend() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CloseSend")
	ret0, _ := ret[0].(error)
	return ret0
}

// CloseSend indicates an expected call of CloseSend.
func (mr *MockStreamMockRecorder[Req, Resp]) CloseSend() *StreamCloseSendCall[Req, Resp] {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CloseSend", reflect.TypeOf((*MockStream[Req, Resp])(nil).CloseSend))
	return &StreamCloseSendCall[Req, Resp]{Call: call}
}

// StreamCloseSendCall wrap *gomock.Call
type StreamCloseSendCall[Req proto.Message, Resp dstreamreader.Response] struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *StreamCloseSendCall[Req, Resp]) Return(arg0 error) *StreamCloseSendCall[Req, Resp] {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *StreamCloseSendCall[Req, Resp]) Do(f func() error) *StreamCloseSendCall[Req, Resp] {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *StreamCloseSendCall[Req, Resp]) DoAndReturn(f func() error) *StreamCloseSendCall[Req, Resp] {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Recv mocks base method.
func (m *MockStream[Req, Resp]) Recv() (Resp, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Recv")
	ret0, _ := ret[0].(Resp)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Recv indicates an expected call of Recv.
func (mr *MockStreamMockRecorder[Req, Resp]) Recv() *StreamRecvCall[Req, Resp] {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Recv", reflect.TypeOf((*MockStream[Req, Resp])(nil).Recv))
	return &StreamRecvCall[Req, Resp]{Call: call}
}

// StreamRecvCall wrap *gomock.Call
type StreamRecvCall[Req proto.Message, Resp dstreamreader.Response] struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *StreamRecvCall[Req, Resp]) Return(arg0 Resp, arg1 error) *StreamRecvCall[Req, Resp] {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *StreamRecvCall[Req, Resp]) Do(f func() (Resp, error)) *StreamRecvCall[Req, Resp] {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *StreamRecvCall[Req, Resp]) DoAndReturn(f func() (Resp, error)) *StreamRecvCall[Req, Resp] {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Send mocks base method.
func (m *MockStream[Req, Resp]) Send(req Req) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Send", req)
	ret0, _ := ret[0].(error)
	return ret0
}

// Send indicates an expected call of Send.
func (mr *MockStreamMockRecorder[Req, Resp]) Send(req any) *StreamSendCall[Req, Resp] {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockStream[Req, Resp])(nil).Send), req)
	return &StreamSendCall[Req, Resp]{Call: call}
}

// StreamSendCall wrap *gomock.Call
type StreamSendCall[Req proto.Message, Resp dstreamreader.Response] struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *StreamSendCall[Req, Resp]) Return(arg0 error) *StreamSendCall[Req, Resp] {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *StreamSendCall[Req, Resp]) Do(f func(Req) error) *StreamSendCall[Req, Resp] {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *StreamSendCall[Req, Resp]) DoAndReturn(f func(Req) error) *StreamSendCall[Req, Resp] {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
