name: test

on:
  pull_request:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.23

      - name: Verify dependencies
        run: go mod verify

      - name: Run tests
        run: |
          go test --tags=test ./internal/... -coverprofile=coverage.txt.tmp

      - name: Filter coverage
        run: |
          cat coverage.txt.tmp | grep -v -e "pb.go" -e "mocks.go" -e "manager.go" -e "db_pool" > coverage.txt && rm coverage.txt.tmp

      - name: Upload code coverage
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  integration-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.23

      - name: Verify dependencies
        run: go mod verify

      - name: Run inline tests
        run: |
          go test -count=1 --tags=inline ./pkg/test/...
